### ISSUE TITLE
Admin/couponManagement/addCoupon

### ISSUE THREAD

**Issue by katisd** [meeorder/meeorder-frontend#61]
Why is there a greyish border here? And the divider line?
![image](https://github.com/meeorder/meeorder-frontend/assets/90249534/e59194c4-5633-4024-8e77-88cc3c800931)

Design 👇
![image](https://github.com/meeorder/meeorder-frontend/assets/90249534/bc831227-7e6e-423a-af3f-98a463dc322b)

**Comment by JiMeow** [comment]
Solve in this PR [solve divider issue](https://github.com/meeorder/meeorder-frontend/pull/73)

**Comment by JiMeow** [comment]
Sorry for late
