### ISSUE TITLE
When you cannot register, it's should be display a reason.

### ISSUE THREAD

**Issue by Vjumpkung** [meeorder/meeorder-frontend#65]
username is already taken : 
![image](https://github.com/meeorder/meeorder-frontend/assets/12080533/004fa8af-83a8-4946-a553-89805e0e2d2e)
username is invalid : 
![image](https://github.com/meeorder/meeorder-frontend/assets/12080533/7e3f7710-d89b-4ada-96e0-3e593f038a54)

**Comment by JiMeow** [comment]
Good good

**Comment by JiMeow** [comment]
Golf solve this issue in this [PR](https://github.com/meeorder/meeorder-frontend/pull/68)
