### ISSUE TITLE
[Menu management] Feed back from Aj.Preeda

### ISSUE THREAD

**Issue by katisd** [meeorder/meeorder-frontend#82]
- [ ] remove edit/add feature Addons

- [ ] remove edit/add feature Ingredient

![image](https://github.com/meeorder/meeorder-frontend/assets/90249534/57bc21fd-814a-44b3-84e6-b14f2ce80975)
![image](https://github.com/meeorder/meeorder-frontend/assets/90249534/f9a9e965-f27b-4f27-bfb0-0c5823a9c9db)

**Comment by JiMeow** [comment]
https://github.com/meeorder/meeorder-frontend/pull/83
